name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Davi-Tlr
          svg_out_path: output/github-contribution-grid-snake.svg
          gif_out_path: output/github-contribution-grid-snake.gif

      - name: Push to GitHub
        uses: github-actions/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: output
